version: '3.8'

volumes:
  duck-node_modules:
    name: duck-node_modules
    external: true

services:
  duckbot:
    build:
      context: .
      args:
        GIT_TOKEN: $GIT_TOKEN
    image:  ghcr.io/dead0duck/duckbot_pg
    container_name: duckbot
    ports:
      - '80:80'
      - '443:443'
      - '3000:3000'
      - '4000:4000'
    volumes:
      - .:/home/container
      - duck-node_modules:/home/container/app/node_modules
    stdin_open: true
    tty: true
    restart: always
